version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
    commit-message:
      prefix: "chore"
    versioning-strategy: "auto"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
    commit-message:
      prefix: "chore"
    versioning-strategy: "auto"
