class Fernet:
    def __init__(self, key: str): ...

    def encrypt(self, data: bytes) -> str: ...

    def generate_new_key(self) -> str: ...

    def decrypt(self, token: str) -> bytes: ...

    def decrypt_with_ttl(self, token: str, ttl_secs: int) -> bytes: ...

class DecryptionError(TypeError): ...