from typing import Sequence

class Fernet:
    def __init__(self, key: str): ...

    def encrypt(self, data: bytes) -> str: ...

    @staticmethod
    def generate_new_key() -> str: ...

    def decrypt(self, token: str) -> bytes: ...

    def decrypt_with_ttl(self, token: str, ttl_secs: int) -> bytes: ...

class MultiFernet:
    def __init__(self, keys: Sequence[str]): ...

    def encrypt(self, data: bytes) -> str: ...

    def decrypt(self, token: str) -> bytes: ...

class DecryptionError(TypeError): ...